port=29500
CUDA_VISIBLE_DEVICES=0 python train.py \
    ddp.master_port=$port \
    method=FIT \
    rlbench.tasks=[stack_blocks] \
    rlbench.task_name='single' \
    rlbench.cameras=[front,left_shoulder,right_shoulder,wrist] \
    rlbench.demos=2 \
    rlbench.demo_path=/home/rutavms/data/peract_single \
    replay.batch_size=8 \
    replay.path=/tmp/replay \
    replay.max_parallel_processes=32 \
    framework.training_iterations=80000 \
    framework.num_weights_to_keep=60 \
    framework.start_seed=0 \
    framework.log_freq=4000 \
    framework.save_freq=4000 \
    framework.logdir=/home/rutavms/research/task_spec/exps/fit_sb_video \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    method.lang_goal_spec=False \
    method.video_goal_spec=True \
    method.image_goal_spec=False \
    ddp.num_devices=1
