port=29500
CUDA_VISIBLE_DEVICES=0 python train.py \
    ddp.master_port=$port \
    method=VIT_BC_LANG \
    rlbench.tasks=[open_drawer] \
    rlbench.task_name='single_1k' \
    rlbench.cameras=[front,left_shoulder,right_shoulder,wrist] \
    rlbench.demos=1000 \
    rlbench.demo_path=/home/rutavms/data/peract_single/train \
    replay.batch_size=64 \
    replay.path=/tmp/replay \
    replay.max_parallel_processes=32 \
    framework.training_iterations=40000 \
    framework.num_weights_to_keep=60 \
    framework.start_seed=0 \
    framework.log_freq=2000 \
    framework.save_freq=2000 \
    framework.logdir=/home/rutavms/research/task_spec/exps \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    ddp.num_devices=1
